### ISSUE TITLE
Could not find style data in module named code-sample-theme

### ISSUE THREAD

**Issue by btopro** [kcmr/code-sample#22] opened 2019-01-28 23:08 UTC
have an element leveraging this (great component btw) and it throws this in console. Don't think this style is exported anywhere for it to leverage.

**Comment by kcmr** [comment] 2020-01-31 20:56
You're right. The component includes a style module named `code-sample-theme` but it doesn't import it directly. You have to create and import that style module from another file. This behavior is intentional to allow using a custom theme. The demo contains an example: https://github.com/kcmr/code-sample/blob/master/demo/code-sample-theme.js

If you don't create and import a custom theme, the messages in console are warnings, so the component should continue working as expected.

I'm closing the issue because it's not a bug.

Thank you for using the component :) 

BTW I'm going to release a new version (v4) in the next days using LitElement and new themes.

**Closed as completed by kcmr** 2020-01-31 20:56 UTC
